### ISSUE TITLE
Issue-Rename ERC23_tokens.sol to all-in-one-base.sol

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#10]
Automated Review Comments
Issues in ERC23_tokens/all-in-one-base.sol:
  - (76, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
