### ISSUE TITLE
Issue-Added missing SafeMath contract.

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#116]
Automated Review Comments
Issues in SafeMath.sol:
  - (25, 'Line exceeds 80 characters')
Issues in token/ERC223/ERC223Basic.sol:
  - (8, 'Line exceeds 80 characters')
Issues in token/ERC223/ERC223BasicToken.sol:
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
