### ISSUE TITLE
Issue-Update README.md

Fixed typo according to review from DavidKnott. More info: https://github.com/OpenZeppelin/zeppelin-solidity/pull/266#discussion_r123003853

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#122]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
