### ISSUE TITLE
Issue-Create LICENSE

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#167]
Automated Review Comments
Issues in LICENSE:
  - (45, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (87, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
  - (474, 'Hardcoded string found')
  - (476, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (484, 'Hardcoded string found')
  - (493, 'Hardcoded string found')
  - (496, 'Hardcoded string found')
  - (508, 'Hardcoded string found')
  - (522, 'Hardcoded string found')
  - (573, 'Hardcoded string found')
  - (594, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (633, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
