### ISSUE TITLE
Issue-

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#2]
Automated Review Comments
Issues in ETC23_tokens.sol:
  - (76, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (160, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
