### ISSUE TITLE
Issue-comments for new functions added

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#20]
Automated Review Comments
Issues in ERC23_token.sol:
  - (6, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
