### ISSUE TITLE
Issue-Add CI

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#202]
Automated Review Comments
Issues in LICENSE:
  - (7, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in README.md:
  - (9, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (71, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (80, 'Line exceeds 80 characters')
  - (91, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')
  - (105, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (110, 'Line exceeds 80 characters')
  - (114, 'Line exceeds 80 characters')
  - (116, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (121, 'Line exceeds 80 characters')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (145, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (154, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (158, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (161, 'Line exceeds 80 characters')
  - (162, 'Line exceeds 80 characters')
  - (165, 'Line exceeds 80 characters')
  - (166, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (171, 'Line exceeds 80 characters')
  - (173, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (179, 'Line exceeds 80 characters')
  - (181, 'Line exceeds 80 characters')
  - (183, 'Line exceeds 80 characters')
  - (185, 'Line exceeds 80 characters')
  - (187, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (200, 'Line exceeds 80 characters')
  - (202, 'Line exceeds 80 characters')
  - (204, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (210, 'Line exceeds 80 characters')
  - (211, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
  - (213, 'Line exceeds 80 characters')
  - (214, 'Hardcoded string found')
  - (215, 'Line exceeds 80 characters')
  - (222, 'Line exceeds 80 characters')
  - (223, 'Hardcoded string found')
  - (226, 'Line exceeds 80 characters')
  - (237, 'Line exceeds 80 characters')
Issues in examples/eth-vanity-address-generator.js:
  - (16, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
Issues in examples/readme.js:
  - (11, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
Issues in index.d.ts:
  - (19, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (20, 'Line exceeds 80 characters')
  - (20, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
Issues in index.js:
  - (2, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (63, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (88, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (120, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (134, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (177, 'Line exceeds 80 characters')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (183, 'Hardcoded string found')
  - (189, 'Line exceeds 80 characters')
  - (189, 'Hardcoded string found')
  - (190, 'Hardcoded string found')
  - (192, 'Line exceeds 80 characters')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (209, 'Line exceeds 80 characters')
  - (211, 'Hardcoded string found')
  - (212, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (229, 'Line exceeds 80 characters')
  - (270, 'Hardcoded string found')
  - (276, 'Line exceeds 80 characters')
  - (276, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (294, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (311, 'Line exceeds 80 characters')
  - (311, 'Hardcoded string found')
  - (329, 'Hardcoded string found')
  - (350, 'Line exceeds 80 characters')
  - (350, 'Hardcoded string found')
  - (355, 'Line exceeds 80 characters')
  - (362, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (367, 'Line exceeds 80 characters')
  - (372, 'Hardcoded string found')
  - (377, 'Hardcoded string found')
  - (378, 'Hardcoded string found')
  - (380, 'Line exceeds 80 characters')
  - (386, 'Line exceeds 80 characters')
  - (386, 'Hardcoded string found')
  - (387, 'Line exceeds 80 characters')
  - (388, 'Hardcoded string found')
  - (391, 'Line exceeds 80 characters')
  - (395, 'Line exceeds 80 characters')
  - (397, 'Line exceeds 80 characters')
  - (397, 'Hardcoded string found')
  - (401, 'Line exceeds 80 characters')
  - (401, 'Hardcoded string found')
  - (403, 'Line exceeds 80 characters')
  - (403, 'Hardcoded string found')
  - (404, 'Line exceeds 80 characters')
  - (408, 'Hardcoded string found')
  - (409, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
Issues in index.ts:
  - (11, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (73, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (78, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (95, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
  - (120, 'Line exceeds 80 characters')
  - (122, 'Line exceeds 80 characters')
  - (122, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (136, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (140, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (147, 'Hardcoded string found')
  - (148, 'Line exceeds 80 characters')
  - (148, 'Hardcoded string found')
  - (150, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (159, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (174, 'Line exceeds 80 characters')
  - (174, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (184, 'Hardcoded string found')
  - (186, 'Line exceeds 80 characters')
  - (186, 'Hardcoded string found')
  - (191, 'Line exceeds 80 characters')
  - (191, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (201, 'Line exceeds 80 characters')
  - (209, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (213, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (218, 'Line exceeds 80 characters')
  - (218, 'Hardcoded string found')
  - (219, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (231, 'Line exceeds 80 characters')
  - (235, 'Hardcoded string found')
  - (236, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (245, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (259, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (268, 'Line exceeds 80 characters')
  - (275, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (282, 'Line exceeds 80 characters')
  - (283, 'Line exceeds 80 characters')
  - (289, 'Line exceeds 80 characters')
  - (289, 'Hardcoded string found')
  - (292, 'Line exceeds 80 characters')
  - (307, 'Line exceeds 80 characters')
  - (308, 'Line exceeds 80 characters')
  - (322, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (324, 'Hardcoded string found')
  - (337, 'Hardcoded string found')
  - (341, 'Line exceeds 80 characters')
  - (341, 'Hardcoded string found')
  - (344, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (350, 'Line exceeds 80 characters')
  - (351, 'Line exceeds 80 characters')
  - (352, 'Hardcoded string found')
  - (353, 'Line exceeds 80 characters')
  - (353, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (371, 'Hardcoded string found')
  - (388, 'Line exceeds 80 characters')
  - (393, 'Hardcoded string found')
  - (404, 'Line exceeds 80 characters')
  - (405, 'Line exceeds 80 characters')
  - (419, 'Line exceeds 80 characters')
  - (425, 'Line exceeds 80 characters')
  - (425, 'Hardcoded string found')
  - (437, 'Line exceeds 80 characters')
  - (439, 'TODO found')
  - (443, 'Hardcoded string found')
  - (447, 'Hardcoded string found')
  - (448, 'Line exceeds 80 characters')
  - (454, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (460, 'Hardcoded string found')
  - (461, 'Line exceeds 80 characters')
  - (468, 'Line exceeds 80 characters')
  - (468, 'Hardcoded string found')
  - (469, 'Line exceeds 80 characters')
  - (471, 'Hardcoded string found')
  - (479, 'Line exceeds 80 characters')
  - (481, 'Hardcoded string found')
  - (485, 'Line exceeds 80 characters')
  - (485, 'Hardcoded string found')
  - (487, 'Line exceeds 80 characters')
  - (487, 'Hardcoded string found')
  - (488, 'Line exceeds 80 characters')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
Issues in rollup.config.js:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in test/eip155.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (64, 'Line exceeds 80 characters')
  - (64, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
  - (72, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (74, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
  - (78, 'Hardcoded string found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (82, 'Line exceeds 80 characters')
  - (82, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (91, 'Line exceeds 80 characters')
  - (91, 'Hardcoded string found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (98, 'Hardcoded string found')
  - (99, 'Line exceeds 80 characters')
  - (99, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (108, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (114, 'Hardcoded string found')
  - (115, 'Line exceeds 80 characters')
  - (115, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (119, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Line exceeds 80 characters')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (132, 'Line exceeds 80 characters')
  - (132, 'Hardcoded string found')
  - (133, 'Line exceeds 80 characters')
  - (133, 'Hardcoded string found')
  - (134, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (142, 'Hardcoded string found')
  - (143, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (145, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (149, 'Line exceeds 80 characters')
  - (149, 'Hardcoded string found')
  - (150, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (158, 'Hardcoded string found')
  - (159, 'Line exceeds 80 characters')
  - (159, 'Hardcoded string found')
  - (160, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (164, 'Hardcoded string found')
  - (165, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (166, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (167, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (174, 'Hardcoded string found')
  - (175, 'Hardcoded string found')
  - (176, 'Line exceeds 80 characters')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (183, 'Line exceeds 80 characters')
  - (183, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
Issues in test/ethers.LICENSE.md:
  - (7, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
Issues in test/test.js:
  - (2, 'Hardcoded string found')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (89, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (131, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (143, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (146, 'Line exceeds 80 characters')
  - (146, 'Hardcoded string found')
  - (147, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (156, 'Hardcoded string found')
  - (157, 'Line exceeds 80 characters')
  - (158, 'Hardcoded string found')
  - (169, 'Line exceeds 80 characters')
  - (176, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (192, 'Line exceeds 80 characters')
  - (196, 'Line exceeds 80 characters')
  - (212, 'Line exceeds 80 characters')
  - (222, 'Line exceeds 80 characters')
  - (232, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
Issues in test/transactions.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Line exceeds 80 characters')
  - (7, 'Hardcoded string found')
  - (8, 'Line exceeds 80 characters')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')

**Comment by kazupot7** [comment]
I got it.
