### ISSUE TITLE
Issue-Add Decentraland's MANA

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#204]
Automated Review Comments
Issues in LICENSE:
  - (8, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
Issues in README.md:
  - (8, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (27, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (46, 'Hardcoded string found')
  - (48, 'Line exceeds 80 characters')
  - (51, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (81, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (87, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
  - (103, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (108, 'Line exceeds 80 characters')
  - (115, 'Line exceeds 80 characters')
  - (117, 'Line exceeds 80 characters')
  - (118, 'Line exceeds 80 characters')
  - (123, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (130, 'Line exceeds 80 characters')
  - (135, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (139, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
  - (141, 'Hardcoded string found')
  - (142, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (153, 'Line exceeds 80 characters')
  - (164, 'Line exceeds 80 characters')
  - (172, 'Line exceeds 80 characters')
  - (176, 'Line exceeds 80 characters')
  - (178, 'Line exceeds 80 characters')
  - (182, 'Line exceeds 80 characters')
  - (185, 'Line exceeds 80 characters')
  - (186, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (190, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (192, 'Line exceeds 80 characters')
  - (195, 'Line exceeds 80 characters')
  - (196, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (199, 'Line exceeds 80 characters')
  - (202, 'Line exceeds 80 characters')
  - (203, 'Line exceeds 80 characters')
  - (206, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (210, 'Line exceeds 80 characters')
  - (214, 'Line exceeds 80 characters')
  - (216, 'Line exceeds 80 characters')
  - (218, 'Line exceeds 80 characters')
  - (220, 'Line exceeds 80 characters')
  - (222, 'Line exceeds 80 characters')
  - (224, 'Line exceeds 80 characters')
  - (226, 'Line exceeds 80 characters')
  - (228, 'Line exceeds 80 characters')
  - (230, 'Line exceeds 80 characters')
  - (232, 'Line exceeds 80 characters')
  - (237, 'Line exceeds 80 characters')
  - (239, 'Line exceeds 80 characters')
  - (241, 'Line exceeds 80 characters')
  - (243, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
