### ISSUE TITLE
Issue-corrections and minor optimization

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#22]
Automated Review Comments
Issues in ERC23_token.sol:
  - (7, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (55, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
