### ISSUE TITLE
Issue-updated contracts to solidity 0.5.0

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#220]
Automated Review Comments
Issues in SafeMath.sol:
  - (30, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (106, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (134, 'Line exceeds 80 characters')
  - (140, 'Line exceeds 80 characters')
Issues in token/ERC223/ERC223_interface.sol:
  - (13, 'Line exceeds 80 characters')
Issues in token/ERC223/ERC223_receiving_contract.sol:
  - (12, 'Line exceeds 80 characters')
Issues in token/ERC223/ERC223_token.sol:
  - (27, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
