### ISSUE TITLE
Issue-Added modular ERC223 token contracts.

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#237]
Automated Review Comments
Issues in token/ERC223/ERC223.sol:
  - (19, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
Issues in token/ERC223/IERC223.sol:
  - (10, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
Issues in token/ERC223/IERC223Recipient.sol:
  - (16, 'Line exceeds 80 characters')
Issues in token/ERC223/README.md:
  - (13, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
