### ISSUE TITLE
Issue-Relocate safeMath library

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#241]
Automated Review Comments
Issues in math/safeMath.sol:
  - (60, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (88, 'Line exceeds 80 characters')
  - (94, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
