### ISSUE TITLE
Issue-Updated description of token contracts and interfaces.

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#251]
Automated Review Comments
Issues in README.md:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
