### ISSUE TITLE
Issue-Typos fixed

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#295]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
