### ISSUE TITLE
Issue-tokenFallback changed to tokenReceived (solidity 0.6.0+)

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#299]
Automated Review Comments
Issues in token/ERC223/ERC223.sol:
  - (20, 'Line exceeds 80 characters')
Issues in token/ERC223/ERC223Mintable.sol:
  - (10, 'Line exceeds 80 characters')
Issues in token/ERC223/IERC223Recipient.sol:
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
