### ISSUE TITLE
Issue-Updates for 0.8.0 solidity

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#305]
Automated Review Comments
Issues in token/ERC223/IERC223Recipient.sol:
  - (24, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
