### ISSUE TITLE
Issue-tokenFallback receiver function should be renamed into tokenReceived

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#307]
Automated Review Comments
Issues in README.md:
  - (10, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
