### ISSUE TITLE
Issue-Solidity 0.8.0 update for ERC223 interface contract

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#313]
Automated Review Comments
Issues in token/ERC223/IERC223.sol:
  - (22, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
