### ISSUE TITLE
Issue-Imports update

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#317]
Automated Review Comments
Issues in token/ERC223/ERC223.sol:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
