### ISSUE TITLE
Issue-Basic cleanup & visibility improvements

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#321]
Automated Review Comments
Issues in token/ERC223/ERC223.sol:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
