### ISSUE TITLE
Issue-first commit

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#349]
Automated Review Comments
Issues in README.md:
  - (2, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
Issues in main.go:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (55, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (116, 'Line exceeds 80 characters')
  - (117, 'Hardcoded string found')
  - (127, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
