### ISSUE TITLE
Issue-Removed the actual implementation of CustomFallback

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#351]
Automated Review Comments
Issues in README.md:
  - (2, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (54, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (68, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (84, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (93, 'Line exceeds 80 characters')
  - (95, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (99, 'Line exceeds 80 characters')
Issues in token/ERC223/ERC223CustomFallback.sol:
  - (2, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (4, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (63, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')
  - (106, 'Line exceeds 80 characters')
  - (128, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
