### ISSUE TITLE
Issue-ERC223 contract custom fallback description

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#363]
Automated Review Comments
Issues in token/ERC223/README.md:
  - (1, 'Line exceeds 80 characters')
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
