### ISSUE TITLE
Issue-added _data to transfer function

As Ether transactions contains _data I think it is needed to be implemented by token transactions too for future use.

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#38]
Automated Review Comments
Issues in ERC23_token.sol:
  - (14, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (57, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (92, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
