### ISSUE TITLE
Issue-Remove bytes4 return to separate branch

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#393]
Automated Review Comments
Issues in token/ERC223/ERC223.sol:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
