### ISSUE TITLE
Issue-Transfer event no longer contains _data

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#46]
Automated Review Comments
Issues in ERC23_token.sol:
  - (10, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (39, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
