### ISSUE TITLE
Issue-Code style formatting

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#56]
Automated Review Comments
Issues in ERC23_token.sol:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (44, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (60, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (76, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
