### ISSUE TITLE
Issue-Create README.md

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#60]
Automated Review Comments
Issues in README.md:
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
  - (12, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')
  - (19, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
