### ISSUE TITLE
Issue-ERC23 tokens added

ERC23 token template itself and SafeMath.

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#8]
Automated Review Comments
Issues in ERC23_token.sol:
  - (12, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (74, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (97, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
