### ISSUE TITLE
Issue-Removed `private` from functions

Removed `private` from `transferToContract` and `transferToAddress` as its implementation details. Not a part of specification.

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#80]
Automated Review Comments
Issues in ERC23_token.sol:
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (24, 'Line exceeds 80 characters')

**Comment by kazupot7** [comment]
I got it.
