### ISSUE TITLE
Issue-Update and rename ERC23_token.sol to ERC223_Token.sol

### ISSUE THREAD

**Issue by kentaurse** [kentaurse/ERC223-token-standard#94]
Automated Review Comments
Issues in ERC223_Token.sol:
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (45, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
